"""update

Revision ID: 346d11a6e533
Revises: 7cf6088ea9a7
Create Date: 2026-04-26 12:53:41.342660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "346d11a6e533"
down_revision: Union[str, Sequence[str], None] = "7cf6088ea9a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_prompts", sa.Column("ID", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "case_prompts", sa.Column("CASE_ID", sa.String(length=255), nullable=False)
    )
    op.add_column("case_prompts", sa.Column("PROMPT", sa.Text(), nullable=False))
    op.add_column(
        "case_prompts", sa.Column("ANGLE_LABEL", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "case_prompts", sa.Column("DRAFT_TYPE", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "case_prompts", sa.Column("DOCUMENTS_COVERED", sa.JSON(), nullable=True)
    )
    op.add_column("case_prompts", sa.Column("GIST_USED", sa.JSON(), nullable=True))
    op.add_column(
        "case_prompts", sa.Column("REFERENCES_USED", sa.JSON(), nullable=True)
    )
    op.add_column("case_prompts", sa.Column("SCORE", sa.Float(), nullable=True))
    op.add_column(
        "case_prompts", sa.Column("SCORE_BREAKDOWN", sa.JSON(), nullable=True)
    )
    op.add_column(
        "case_prompts", sa.Column("CREATED_AT", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "case_prompts", sa.Column("UPDATED_AT", sa.DateTime(), nullable=False)
    )
    op.add_column("case_prompts", sa.Column("METADATA", sa.JSON(), nullable=False))
    op.drop_index(op.f("ix_case_prompts_case_id"), table_name="case_prompts")
    op.create_index(
        op.f("ix_case_prompts_CASE_ID"), "case_prompts", ["CASE_ID"], unique=False
    )
    op.create_foreign_key(None, "case_prompts", "cases", ["CASE_ID"], ["ID"])
    op.drop_column("case_prompts", "id")
    op.drop_column("case_prompts", "gist_used")
    op.drop_column("case_prompts", "references_used")
    op.drop_column("case_prompts", "score_breakdown")
    op.drop_column("case_prompts", "prompt")
    op.drop_column("case_prompts", "created_at")
    op.drop_column("case_prompts", "case_id")
    op.drop_column("case_prompts", "angle_label")
    op.drop_column("case_prompts", "documents_covered")
    op.drop_column("case_prompts", "draft_type")
    op.drop_column("case_prompts", "score")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_prompts",
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "draft_type", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "documents_covered",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "angle_label", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column("case_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column("prompt", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "references_used",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "case_prompts",
        sa.Column(
            "gist_used",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "case_prompts", sa.Column("id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "case_prompts", type_="foreignkey")
    op.drop_index(op.f("ix_case_prompts_CASE_ID"), table_name="case_prompts")
    op.create_index(
        op.f("ix_case_prompts_case_id"), "case_prompts", ["case_id"], unique=False
    )
    op.drop_column("case_prompts", "METADATA")
    op.drop_column("case_prompts", "UPDATED_AT")
    op.drop_column("case_prompts", "CREATED_AT")
    op.drop_column("case_prompts", "SCORE_BREAKDOWN")
    op.drop_column("case_prompts", "SCORE")
    op.drop_column("case_prompts", "REFERENCES_USED")
    op.drop_column("case_prompts", "GIST_USED")
    op.drop_column("case_prompts", "DOCUMENTS_COVERED")
    op.drop_column("case_prompts", "DRAFT_TYPE")
    op.drop_column("case_prompts", "ANGLE_LABEL")
    op.drop_column("case_prompts", "PROMPT")
    op.drop_column("case_prompts", "CASE_ID")
    op.drop_column("case_prompts", "ID")
    # ### end Alembic commands ###
