"""update

Revision ID: 4be3be5b9dbd
Revises: 346d11a6e533
Create Date: 2026-04-28 19:04:01.548230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4be3be5b9dbd"
down_revision: Union[str, Sequence[str], None] = "346d11a6e533"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drafts",
        sa.Column("ID", sa.String(length=255), nullable=False),
        sa.Column("CASE_ID", sa.String(length=255), nullable=False),
        sa.Column("CASE_PROMPT_ID", sa.String(length=255), nullable=False),
        sa.Column("DRAFT_TYPE", sa.String(length=64), nullable=False),
        sa.Column(
            "STATUS",
            sa.Enum("DRAFT_V0", "UNDER_REVISION", "FINAL", name="draft_status_enum"),
            nullable=False,
        ),
        sa.Column("CONTENT", sa.JSON(), nullable=False),
        sa.Column("RAW_CONTENT", sa.Text(), nullable=False),
        sa.Column("VERSION", sa.Integer(), nullable=False),
        sa.Column("DRAFT_LANGUAGE", sa.String(length=32), nullable=False),
        sa.Column("VALIDATION_SCORE", sa.Float(), nullable=True),
        sa.Column(
            "VALIDATION_STATUS",
            sa.Enum("VALID", "NEEDS_REVISION", name="validation_status_enum"),
            nullable=True,
        ),
        sa.Column("VALIDATION_ISSUES", sa.JSON(), nullable=True),
        sa.Column("VALIDATION_PASSED_CHECKS", sa.JSON(), nullable=True),
        sa.Column("REVISIONS", sa.JSON(), nullable=False),
        sa.Column("CREATED_AT", sa.DateTime(), nullable=False),
        sa.Column("UPDATED_AT", sa.DateTime(), nullable=False),
        sa.Column("METADATA", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["CASE_ID"],
            ["cases.ID"],
        ),
        sa.ForeignKeyConstraint(
            ["CASE_PROMPT_ID"],
            ["case_prompts.ID"],
        ),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_index(op.f("ix_drafts_CASE_ID"), "drafts", ["CASE_ID"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drafts_CASE_ID"), table_name="drafts")
    op.drop_table("drafts")
    # ### end Alembic commands ###
