"""update

Revision ID: 7aab410534ed
Revises: 359c4b6a9198
Create Date: 2026-04-21 17:13:45.044175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7aab410534ed"
down_revision: Union[str, Sequence[str], None] = "359c4b6a9198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_USER_ID"), table_name="cases")
    op.create_index(op.f("ix_cases_USER_ID"), "cases", ["USER_ID"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_USER_ID"), table_name="cases")
    op.create_index(op.f("ix_cases_USER_ID"), "cases", ["USER_ID"], unique=True)
    # ### end Alembic commands ###
