"""update

Revision ID: 7cf6088ea9a7
Revises: 4ae1ef6789ee
Create Date: 2026-04-26 12:24:35.488040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7cf6088ea9a7"
down_revision: Union[str, Sequence[str], None] = "4ae1ef6789ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("angle_label", sa.String(length=64), nullable=True),
        sa.Column("draft_type", sa.String(length=64), nullable=True),
        sa.Column(
            "documents_covered", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("gist_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "references_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_prompts_case_id"), "case_prompts", ["case_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_prompts_case_id"), table_name="case_prompts")
    op.drop_table("case_prompts")
    # ### end Alembic commands ###
